export default {
  data: [
    {
      id: 52,
      type: 14,
      subType: null,
      purpose: '前三个月月均运费',
      value: '111',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 1,
      subList: null,
    },
    {
      id: 53,
      type: 14,
      subType: null,
      purpose: '前三个月其中一个月运费',
      value: '112',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 1,
      subList: null,
    },
    {
      id: 222,
      type: 14,
      subType: null,
      purpose: '截至目前本月运费',
      value: '112',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 0,
      subList: null,
    },
    {
      id: 54,
      type: 15,
      subType: null,
      purpose: '前三个月月均运费',
      value: '50000',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 1,
      subList: null,
    },
    {
      id: 55,
      type: 15,
      subType: null,
      purpose: '前三个月其中一个月运费',
      value: '50000',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 0,
      subList: null,
    },
    {
      id: 223,
      type: 15,
      subType: null,
      purpose: '截至目前本月运费',
      value: '500',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 1,
      subList: null,
    },
    {
      id: 56,
      type: 16,
      subType: null,
      purpose: '前三个月月均运费',
      value: '50000',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 0,
      subList: null,
    },
    {
      id: 57,
      type: 16,
      subType: null,
      purpose: '前三个月其中一个月运费',
      value: '52654',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 1,
      subList: null,
    },
    {
      id: 224,
      type: 16,
      subType: null,
      purpose: '截至目前本月运费',
      value: '500',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 1,
      subList: null,
    },
    {
      id: 58,
      type: 17,
      subType: null,
      purpose: '前三个月月均运费',
      value: '50000',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 1,
      subList: null,
    },
    {
      id: 59,
      type: 17,
      subType: null,
      purpose: '前三个月其中一个月运费',
      value: '155441',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 1,
      subList: null,
    },
    {
      id: 225,
      type: 17,
      subType: null,
      purpose: '截至目前本月运费',
      value: '50000',
      unit: '元',
      creatorEmpCode: null,
      deleteFlag: 0,
      subList: null,
    },
    {
      id: 51,
      type: 18,
      subType: null,
      purpose: '相较前一日下滑比例',
      value: '40',
      unit: '%',
      creatorEmpCode: null,
      deleteFlag: 0,
      subList: null,
    },
    {
      id: 49,
      type: 19,
      subType: null,
      purpose: '相较前一日下滑比例',
      value: '30',
      unit: '%',
      creatorEmpCode: null,
      deleteFlag: 0,
      subList: null,
    },
    {
      id: 50,
      type: 20,
      subType: null,
      purpose: '相较前一日下滑比例',
      value: '45',
      unit: '%',
      creatorEmpCode: null,
      deleteFlag: 0,
      subList: null,
    },
    {
      id: 48,
      type: 21,
      subType: null,
      purpose: '相较前一日下滑比例',
      value: '50',
      unit: '%',
      creatorEmpCode: null,
      deleteFlag: 0,
      subList: null,
    },
  ],
};
